/**
 * Copyright (c) 2013-2016, Damian Vicino
 * Carleton University, Universite de Nice-Sophia Antipolis
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef CADMIUM_PDEVS_SIMULATOR_HPP
#define CADMIUM_PDEVS_SIMULATOR_HPP
#include <cadmium/modeling/message_bag.hpp>
#include <cadmium/concept/atomic_model_assert.hpp>
#include <boost/optional.hpp>

/**
 * Simulator implementation for atomic models
 */
namespace cadmium {
    namespace engine {
        template<template<typename T> class MODEL, typename TIME> //, typename DEBUG=std::false_type>
        //TODO: implement the debugging
        class simulator {
            using input_ports=typename MODEL<TIME>::input_ports;
            using input_bags=typename make_message_bags<input_ports>::type;
            using output_ports=typename MODEL<TIME>::output_ports;
            using in_bags_type=typename make_message_bags<input_ports>::type;
            using out_bags_type=typename make_message_bags<output_ports>::type;
            MODEL<TIME> _model;
            TIME _last;
            TIME _next;
            boost::optional<in_bags_type> _inbox;
            boost::optional<out_bags_type> _outbox;
        public:
            using model_type=MODEL<TIME>;

            /**
             * @brief simulator constructs by default
             *
             * TODO: create a single parameter constructor receiving init time and remove the init function
             * It will require to call constructors from constructor in coordinator.
             */
//            simulator(){}

            /**
             * @brief constructor is used as init function, sets the start time
             * @param t is the start time
             * @return the time until first time advance result
             */
            void init(TIME initial_time) {
                _last=initial_time;
                cadmium::concept::atomic_model_assert<MODEL>();
                _next = initial_time + _model.time_advance();
            }


            TIME next() const noexcept{
                return _next;
            }

            void collect_outputs(const TIME &t) {
                if (_next < t)
                    throw std::domain_error("Trying to obtain output when not internal event is scheduled");
                else if (_next == t)
                    _outbox = _model.output();
                else
                    _outbox = boost::optional<out_bags_type>();
            }

            /**
             * @brief outbox keeps the output generated by the last call to collect_outputs
             * The value is optional, telling if last collect_output was intended for this coordinated model or not
             */
            boost::optional<out_bags_type> outbox() const noexcept{
                return _outbox;
            }


            /**
             * @brief inbox keeps the input introduced by upper level coordinator for running next advance_simulation
             * The value is optional, and set to false at the exit fo each advance to prevent reruns
             */
            void inbox(boost::optional<in_bags_type> in) noexcept{
                _inbox=in;
            }

            /**
             * @brief advanceSimulation advances the execution to t, at t introduces the messages into the system (if any).
             * @param t is the time the transition is expected to be run.
            */
            void advance_simulation(TIME t) {
                if (t < _last) {
                    throw std::domain_error("Event received for executing in the past of current simulation time");
                } else if (_next < t) {
                    throw std::domain_error("Event received for executing after next internal event");
                } else {
                    if (_inbox) { //input available
                        if (t == _next) { //confluence
                            _model.confluence_transition(t - _last, *_inbox);
                        } else { //external
                            _model.external_transition(t - _last, *_inbox);
                        }
                    } else { //no input available
                        if (t != _next) {
                            throw std::domain_error("Trying to execute internal transition at wrong time");
                        } else {
                            _model.internal_transition();
                        }
                    }
                    _last = t;
                    _next = _last + _model.time_advance();
                    _inbox = boost::optional<in_bags_type>{};
                }
            }
    //TODO: use enable_if functions to give access to read state and messages in debug mode

        private:
            //auxiliary
            template<size_t I, typename... Ps>
            struct all_bags_empty_impl {
                static bool check(std::tuple<Ps...> t) {
                    if (!std::get<I - 1>(t).messages.empty()) return false;
                    return all_bags_empty_impl<I - 1, Ps...>::check(t);
                }
            };

            template<typename... Ps>
            struct all_bags_empty_impl<0, Ps...> {
                static bool check(std::tuple<Ps...> t) {
                    return true;
                }
            };

            template<typename... Ps>
            bool all_bags_empty(std::tuple<Ps...> t) {
                return (std::tuple_size < std::tuple < Ps...>>() == 0 )
                || all_bags_empty_impl<std::tuple_size<decltype(t)>::value, Ps...>::check(t);
            }
        };

    }

}

#endif // CADMIUM_PDEVS_SIMULATOR_HPP

